packages:
  - packages/*
  - demo

allowBuilds:
  esbuild: true
  nx: true

catalog:
  '@nx/eslint': 22.6.3
  '@nx/js': 22.6.3
  '@nx/vite': 22.6.3
  '@sinclair/typebox': ^0.34.38
  '@tailwindcss/vite': ^4.1.18
  '@types/node': 18.16.9
  '@types/react': ^19.2.9
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^6.0.2
  cli-forge: ^1.9.2
  nx: 22.6.3
  nx-github-pages: ^1.0.0
  react: ^19.2.3
  react-dom: ^19.2.3
  tailwindcss: ^4.1.18
  tsx: ^4.22.4
  typescript: 5.9.3
  vike: ^0.4.256
  vike-react: ^0.6.19
  vite: ^8.0.0
  vitest: ^4.1.4
  yaml: ^2.8.3
